baseURL = 'https://climbing.uwaterloo.ca/'
languageCode = 'en-us'
title = 'UWCC'
theme = 'paper'
paginate = 5


[params]
  color = 'light'

  instagram = 'uwclimbingclub'
  discord = 'vwwpwvcBXA'

  avatar = 'logo'
  name = 'University of Waterloo Climbing Club'
  bio = 'We like to climb.'

  monoDarkIcon = true


[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events/"
    weight = 3

  [[menu.main]]
    identifier = 'membership'
	name = 'Membership'
	url = 'https://warrior.uwaterloo.ca/membership/GetMembershipSummary?membershipProductId=dc3ed568-3fae-41d2-aa32-e4bc5be6dd85'
	weight = 4


[markup.goldmark.renderer]
  unsafe = true
