baseURL = 'https://climbing.uwaterloo.ca/'
languageCode = 'en-us'
title = 'UW Climbing Club'
theme = 'paper'
paginate = 5
enableEmoji = true


[params]
  color = 'light'
  monoDarkIcon = true

  instagram = 'uwclimbingclub'
  discord = 'BZzNzNq5Up'

  name = 'Welcome! 👋'
  bio = "We're the University of Waterloo Climbing Club."

  logo = 'club_logo.svg'


[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events/"
    weight = 3

  [[menu.main]]
    identifier = 'membership'
    name = 'Membership'
    url = '/membership/'
    weight = 4 


[markup.goldmark.renderer]
  unsafe = true
